# Generated by Django 4.2 on 2023-05-05 17:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0003_remove_studio_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founder_name', models.CharField(max_length=255)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('product_types', multiselectfield.db.fields.MultiSelectField(choices=[('Movie', 'Movie'), ('Short', 'Shorts'), ('Series', 'Series'), ('Cartoon', 'Cartoons'), ('Anime', 'Animes'), ('Music', 'Musics'), ('Premier', 'Premiers')], max_length=7)),
                ('employee_count', models.IntegerField(default=1)),
                ('profit', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('video', models.FileField(null=True, upload_to='media/studio/video/%Y/%m/%d')),
                ('logo', models.ImageField(null=True, upload_to='images/studio/logo/')),
                ('award', models.CharField(blank=True, max_length=255, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.news')),
            ],
            options={
                'verbose_name': 'Studio',
                'verbose_name_plural': 'Studios',
            },
        ),
        migrations.AddIndex(
            model_name='studio',
            index=models.Index(fields=['name'], name='studio_stud_name_51a9c5_idx'),
        ),
    ]
