# Generated by Django 4.2 on 2023-05-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_studio_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/studio/logo/'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/studio/video/%Y/%m/%d'),
        ),
    ]
