# Generated by Django 4.2 on 2023-05-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('studio', '0003_alter_studio_logo_alter_studio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
