# Generated by Django 4.2 on 2023-05-01 08:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/category/logo/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contnent', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founder_name', models.CharField(max_length=255)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('product_types', models.CharField(choices=[('Movie', 'Movie'), ('Short', 'Shorts'), ('Series', 'Series'), ('Cartoon', 'Cartoons'), ('Anime', 'Animes'), ('Music', 'Musics'), ('Premier', 'Premiers')], default=None, max_length=20)),
                ('employee_count', models.IntegerField(default=1)),
                ('profit', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('video', models.FileField(null=True, upload_to='media/studio/video/%Y/%m/%d')),
                ('logo', models.ImageField(null=True, upload_to='images/studio/logo/')),
                ('award', models.CharField(blank=True, max_length=255, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='movie.tag'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('production_year', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('screenwriter', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('montage', models.CharField(max_length=255)),
                ('world_premier_date', models.DateField()),
                ('world_rating', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default=0, max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('cast', models.CharField(max_length=256)),
                ('brief_information', models.TextField()),
                ('trailer', models.FileField(upload_to='media/movie/trailes/')),
                ('logo', models.ImageField(upload_to='images/movie/logo/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_limit', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category')),
                ('genre', models.ManyToManyField(to='movie.genre')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.studio')),
                ('tag', models.ManyToManyField(to='movie.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=movie.models.get_image_upload_path)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.news')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.studio')),
            ],
        ),
    ]
