# Generated by Django 4.2 on 2023-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='product_types',
            field=models.CharField(blank=True, choices=[('Movie', 'Movie'), ('Short', 'Shorts'), ('Series', 'Series'), ('Cartoon', 'Cartoons'), ('Anime', 'Animes'), ('Music', 'Musics'), ('Premier', 'Premiers')], max_length=20, null=True),
        ),
    ]
