# Generated by Django 4.2 on 2023-05-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_genre_created_at_genre_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='news',
        ),
    ]
