# Generated by Django 4.2 on 2023-05-01 09:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_slug_alter_studio_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='product_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Movie', 'Movie'), ('Short', 'Shorts'), ('Series', 'Series'), ('Cartoon', 'Cartoons'), ('Anime', 'Animes'), ('Music', 'Musics'), ('Premier', 'Premiers')], max_length=7),
        ),
    ]
