# Generated by Django 4.2 on 2023-05-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_studio_news'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.ManyToManyField(to='studio.studio'),
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
