# Generated by Django 4.2 on 2023-05-01 09:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_studio_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
