# Generated by Django 4.2 on 2023-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_image_studio_alter_movie_studio_delete_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(upload_to='images/movie/logo/'),
        ),
    ]
