# Generated by Django 4.2 on 2023-05-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('movie', '0005_alter_movie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='actor.actor'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
