# Generated by Django 4.2 on 2023-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='studio',
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_rating',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default=2, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(to='movie.category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ManyToManyField(to='movie.studio'),
        ),
    ]
