# Generated by Django 4.2 on 2023-05-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_image_news_alter_movie_tag_delete_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/movie/logo/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='media/movie/trailes/'),
        ),
    ]
