# Generated by Django 4.2 on 2023-05-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_cast_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contnent',
            new_name='content',
        ),
    ]
