# Generated by Django 4.2 on 2023-05-09 14:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0005_alter_movie_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brief_info', models.CharField(max_length=300)),
                ('birth_place', models.CharField(max_length=255)),
                ('citizenship', django_countries.fields.CountryField(max_length=2)),
                ('career', models.CharField(max_length=50)),
                ('information', models.TextField()),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
            },
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['name'], name='actor_major_name_5efb5d_idx'),
        ),
        migrations.AddField(
            model_name='actor',
            name='genre',
            field=models.ManyToManyField(to='movie.genre'),
        ),
        migrations.AddField(
            model_name='actor',
            name='status',
            field=models.ManyToManyField(to='actor.major'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['name'], name='actor_actor_name_4cda6c_idx'),
        ),
    ]
