# Generated by Django 4.2 on 2023-05-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='about'),
        ),
    ]
